#!/usr/bin/env bash

# Exit when a command fails
set -o errexit

# Exit when use undeclared variables
set -o nounset

init() {
  sudo apt update -y
  sudo apt upgrade -y
  
  ./roles/ssh/main
  ./roles/programs/main
  ./roles/dotfiles/main
  ./roles/shell/main
}

init "$@"
