#!/usr/bin/env bash

# Exit when a command fails
set -o errexit

# Exit when use undeclared variables
set -o nounset

init() {
  sudo apt update -y
  sudo apt upgrade -y
  
  ./actions/get_ssh_keys
  install_programs
  ./actions/get_dotfiles
  ./actions/set_gnome_tweaks_settings
  ./actions/change_shell_to_zsh
  ./actions/update_hosts_file
}

# Install programs
install_programs() {
  ./actions/programs/apt_install
  ./actions/programs/snap_install

  # Install NVM
  wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install | bash
}

init "$@"
