#!/usr/bin/env bash

install() {
  which $1 &> /dev/null

  if [ $? -ne 0 ]; then
    ./bin/success "Installing: ${1}..."
    sudo apt install -y $1
    ./bin/success "Installed: ${1}"
  else
    ./bin/success "Already installed: ${1}"
  fi
}

# Nextcloud source
sudo add-apt-repository ppa:nextcloud-devs/client

sudo apt update -y

install curl
install zsh
install vim
install neovim
install vim-gtk
install git
install wget
install rsync
install zip
install make
install gettext
install gnome-tweaks
install gnome-screensaver
install nfs-common
install fonts-powerline

# Apps
install terminator
install nextcloud-client
install nextcloud-client-nautilus
install gnome-contacts
install ranger
