#!/usr/bin/env bash

install() {
  which $1 &> /dev/null

  if [ $? -ne 0 ]; then
    ./bin/success "Installing: ${1}..."
    sudo apt install -y $1
    ./bin/success "Installed: ${1}"
  else
    ./bin/success "Already installed: ${1}"
  fi
}

sudo apt update -y

install curl
install zsh
install vim
install neovim
install vim-gtk
install git
install make
install jq
build-essential
install gnome-tweaks
install gnome-screensaver
#install fonts-powerline
install fonts-font-awesome
install gnome-shell-extension-manager

# FZF
git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
~/.fzf/install

# Apps
install terminator
install nextcloud-desktop
install ranger
