#!/usr/bin/env bash

install() {
 snap list $1 &> /dev/null

  if [ $? -ne 0 ]; then
    ./bin/success "Installing via snap: "$1"..."
    sudo snap install "$1" $2
    ./bin/success "Installed: ${1}"
  else
    ./bin/success "Already installed: ${1}"
  fi
}

install spotify
install discord
install slack
install teams-for-linux
install vlc
install chromium
