#!/usr/bin/env bash

install() {
  which $1 &> /dev/null

  if [ $? -ne 0 ]; then
    ./bin/success "Installing: ${1}..."
    sudo apt install -y $1
    ./bin/success "Installed: ${1}"
  else
    ./bin/success "Already installed: ${1}"
  fi
}

# Nextcloud source
sudo add-apt-repository ppa:nextcloud-devs/client

# Brave source
install apt-transport-https curl gnupg
curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list

sudo apt update -y

install curl
install zsh
install vim
install vim-gtk
install git
install wget
install rsync
install zip
install make
install gettext

# LAMP
install apache2
install php
install libapache2-mod-php
install mysql-server
install php-mysql
install php-curl
install php-gd
install php-intl
install php-json
install php-mbstring
install php-xml
install php-zip

# Apps
install terminator
install gnome-tweaks
install spotify-client
install nextcloud-client
install nextcloud-client-nautilus
install stacer
install brave-browser
install indicator-multiload
