#!/usr/bin/env bash

sudo apt install -y i3 rofi lxappearance playerctl xbrightlight maim xclip blueman feh libpam0g-dev libx11-xcb-dev

# i3-gaps
sudo add-apt-repository ppa:kgilmer/speed-ricer && apt update && apt install -y i3-gaps

# polybar
sudo apt install -y fonts-font-awesome build-essential cmake cmake-data pkg-config python3-sphinx libcairo2-dev libxcb1-dev libxcb-util0-dev libxcb-randr0-dev libxcb-composite0-dev python3-xcbgen xcb-proto libxcb-image0-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-xkb-dev libxcb-xrm-dev libxcb-cursor-dev libasound2-dev libpulse-dev i3-wm libjsoncpp-dev libmpdclient-dev libcurl4-openssl-dev libnl-genl-3-dev
git clone --recursive https://github.com/polybar/polybar ~/Lab/github/polybar
(
  cd ~/Lab/github/polybar
  ./build.sh
)

# dunst
sudo apt purge dunst
sudo apt install libdbus-1-dev libx11-dev libxinerama-dev libxrandr-dev libxss-dev libglib2.0-dev libpango1.0-dev libgtk-3-dev libxdg-basedir-dev libnotify-dev
git clone https://github.com/dunst-project/dunst.git ~/Lab/github/dunst
(
  cd ~/Lab/github/dunst
  make
  sudo make install
)
