#!/usr/bin/env bash

sudo apt purge dunst
sudo apt install libdbus-1-dev libx11-dev libxinerama-dev libxrandr-dev libxss-dev libglib2.0-dev libpango1.0-dev libgtk-3-dev libxdg-basedir-dev libnotify-dev
git clone https://github.com/dunst-project/dunst.git "${GITHUB_DIR}"/dunst
(
  cd "${GITHUB_DIR}"/dunst
  make
  sudo make install
)
