#!/usr/bin/env bash

git clone https://github.com/deuill/i3-gnome-flashback.git "${GITHUB_DIR}"/i3-gnome-flashback
(
  cd "${GITHUB_DIR}"/i3-gnome-flashback
  sudo make install
)
gsettings set org.gnome.gnome-flashback desktop false
gsettings set org.gnome.gnome-flashback status-notifier-watcher false # To display tray icons
gsettings set org.gnome.gnome-flashback notifications false # To disable gnome default notification daemon