#!/usr/bin/env bash

./bin/success "Changing shell to ZSH..."

chsh -s $(which zsh)
./bin/success "Shell is set to ZSH for $(whoami)"

sudo chsh -s $(which zsh)
./bin/success "Shell is set to ZSH for root"