#!/usr/bin/env bash

# Install dash to dock
dash_to_dock_dir=~/Lab/gnome-extensions/dash-to-dock
dash_to_dock_tag="gnome-3-36"
if [ ! -d "${dash_to_dock_dir}" ]; then
  git clone -b ${dash_to_dock_tag} https://github.com/micheleg/dash-to-dock.git "${dash_to_dock_dir}" 
  (
    cd "${dash_to_dock_dir}"
    make
    make install
  )
  ./bin/success "'Dash to dock' has been installed with branch $dash_to_dock_tag"
fi

# Install Multi Monitors
# https://github.com/spin83/multi-monitors-add-on
multi_monitor_dir=~/Lab/gnome-extensions/multi-monitors-add-on
multi_monitor_tag="gnome-3-32_3-36"
if [ ! -d "${multi_monitor_dir}" ]; then
  git clone -b ${multi_monitor_tag} git://github.com/spin83/multi-monitors-add-on.git "${multi_monitor_dir}" 
  (
    cd "${multi_monitor_dir}"
    cp -r multi-monitors-add-on@spin83 ~/.local/share/gnome-shell/extensions/
  )
  ./bin/success "'Multi Monitors' has been installed with branch $multi_monitor_tag"
fi

# Set settings
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
gsettings set org.gnome.desktop.interface show-battery-percentage true
gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.interface gtk-enable-primary-paste false

gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize,appmenu:'

gsettings set org.gnome.shell.extensions.dash-to-dock dock-position 'BOTTOM'
gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 40
gsettings set org.gnome.shell.extensions.dash-to-dock height-fraction 0.9
gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 40
gsettings set org.gnome.shell.extensions.dash-to-dock show-show-apps-button false
gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed true
gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-shrink true

gsettings set org.gnome.desktop.session idle-delay 'uint32 0'

#gsettings set org.gnome.nautilus.desktop trash-icon-visible false

gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Super>ampersand']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Super>eacute']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Super>quotedbl']"
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Super>apostrophe']"

gsettings set org.gnome.mutter.keybindings toggle-tiled-right "['<Alt><Super>Right']"
gsettings set org.gnome.mutter.keybindings toggle-tiled-right "['<Alt><Super>Right']"
gsettings set org.gnome.desktop.wm.keybindings maximize "['<Alt><Super>f']"

./bin/success "All gnome tweaks settings have been installed."
