#!/usr/bin/env bash

gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
gsettings set org.gnome.desktop.interface show-battery-percentage true
gsettings set org.gnome.desktop.interface clock-show-date true
gsettings set org.gnome.desktop.interface gtk-enable-primary-paste false

gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize,appmenu:'

gsettings set org.gnome.shell.extensions.dash-to-dock dock-position 'BOTTOM'
gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 40

gsettings set org.gnome.desktop.session idle-delay 'uint32 0'

./bin/success "All gnome tweaks settings have been installed."
