#!/usr/bin/env bash

install() {
  ../success "Installing via snap: "$1"..."
  sudo snap install "$1" $2
  ../success "Installed: ${1}"
}

install zoom-client

install code --classic
install slack --classic